### ISSUE TITLE
[Docs] Tensor value has no attribute 'argmax'

### ISSUE THREAD

**Issue by Str-Gen** [modularml/max#278]
### Where is the problem?

https://docs.modular.com/max/tutorials/get-started-with-max-graph

### What can we do better?

In the max-graph-api example in the mnist.mojo file the compiler warns about a missing operation for a Tensor.
specifically probs.argmax(axis=1)  'Tensor[float32]' value has no attribute 'argmax'. Later use of the predicted variable is then recognized as not possible. 
There is an [arg_max operation for Graphs](https://docs.modular.com/max/api/mojo/graph/ops/reduction/arg_max), but I would like to follow the example and not add the argmax to the Graph itself. 
The mojo changelog mentions for version 24.2 that

> The Tensor type now has [argmax()](https://docs.modular.com/mojo/stdlib/tensor/tensor/Tensor#argmax) and [argmin()](https://docs.modular.com/mojo/stdlib/tensor/tensor/Tensor#argmin) functions to compute the position of the max or min value. Note: this should return a Tensor[Int] but currently the output tensor is the same type as the input tensor. This will be fixed in a future release.

Since these operations are no longer implemented for the Tensor type, what should an idiomatic mojo solution look like?

```mojo
probs = output.get[DType.float32]("output0")        
predicted = probs.argmax(axis=1) # this won't compile with max & mojo 24.6

label_ = Tensor[DType.index](TensorShape(1), int(label))
correct += int(predicted == label_)
```

### Anything else?

I'm using the currently latest release of max and mojo (24.6).

**Comment by ehsanmok** [comment]
It was removed in favour of better implementation later. Also discussed [here](https://forum.modular.com/t/stdlib-argmin-and-argmax-functions-removed/374). The Mojo API is unstable  so please use the Python API. We'll update the examples later.

**Comment by iamtimdavis** [comment]
We will fix this in an upcoming release :)
